var studentNames;
var studnentNames;
var studentId;
var MultipleTypes;
studentNames = ["md", "ariful", "islam", "polash"];
studentNames.push("zamil", "hobby", "nabil", "zomir");
studentNames.pop();
studentNames.sort();
MultipleTypes = ["name", 1, 0, 20, 37, "jahirul", "amena", true];
console.log(studentNames);
console.log(studentNames[2]);
console.log(MultipleTypes[1]);
console.log(MultipleTypes[0]);
console.log(MultipleTypes);
MultipleTypes.sort();
console.log(MultipleTypes);
